import sys
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
CODE_ROOT = Path(__file__).resolve().parents[1]
if str(CODE_ROOT) not in sys.path:
    sys.path.insert(0, str(CODE_ROOT))


class TestLayoutTargets(unittest.TestCase):
    def test_code_layout_has_prep_and_experiments_targets(self):
        self.assertTrue((REPO_ROOT / "code" / "prep" / "raw_to_unified").is_dir())
        self.assertTrue((REPO_ROOT / "code" / "prep" / "unified_to_p").is_dir())
        self.assertTrue((REPO_ROOT / "code" / "prep" / "to_pp").is_dir())
        self.assertTrue((REPO_ROOT / "code" / "experiments").is_dir())
        self.assertTrue((REPO_ROOT / "code" / "configs" / "modes").is_dir())
        self.assertTrue((REPO_ROOT / "code" / "configs" / "presets").is_dir())

    def test_runtime_artifacts_are_not_kept_in_code_root(self):
        for name in ["Logs", "Checkpoints", "runs", "Data"]:
            self.assertFalse(
                (REPO_ROOT / "code" / name).exists(),
                f"{name} should live outside code/ or be regenerated by tools",
            )

    def test_auxiliary_script_implementations_are_grouped(self):
        grouped = [
            REPO_ROOT / "code" / "prep" / "unified_to_p" / "reprocess_drozy.py",
            REPO_ROOT / "code" / "prep" / "to_pp" / "reprocess_wesad_pp.py",
            REPO_ROOT / "code" / "experiments" / "downstream_eval.py",
        ]
        for path in grouped:
            self.assertTrue(path.exists(), f"missing grouped implementation: {path}")

        for wrapper in ["reprocess_drozy.py", "downstream_eval.py"]:
            self.assertLess(
                (REPO_ROOT / "code" / wrapper).stat().st_size,
                1000,
                f"{wrapper} should remain a thin compatibility entrypoint",
            )

    def test_existing_flat_import_style_still_works(self):
        import data  # noqa: F401
        import model  # noqa: F401
        import train  # noqa: F401


if __name__ == "__main__":
    unittest.main()
